### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by FrancisBourre** [tondy67/abvkit#1]
Hi. This project looks amazing. Is it ready to use or would you recommend to wait for playing with it.
A quickstart/warnings readme file would be awesome. 
Thanks for all.

**Comment by tondy67** [comment]
hi,
the PEG parser itself is ready to use.
you can test it with hscript, java grammars or your own :)
i working on "universal" AST and grammars for all haxe targets  - js,java,C++,python etc 
for the moment i have done hscript grammar with types, something like simplified haxe, with AST, interpreter and compiler to haxe. i'll do also compiler to js,c,java.
my idea is to be selfhosted project with ability to compile every haxe target to haxe.
for example: java -> haxe ->java
i not update the project yet because it's difficult to adjust all those grammars to "universal ast"
:)
